package me.zsr.feeder.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.zsr.feeder.dao.Feed;
import me.zsr.feeder.dao.RSSItem;

import me.zsr.feeder.dao.FeedDao;
import me.zsr.feeder.dao.RSSItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig feedDaoConfig;
    private final DaoConfig rSSItemDaoConfig;

    private final FeedDao feedDao;
    private final RSSItemDao rSSItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        feedDaoConfig = daoConfigMap.get(FeedDao.class).clone();
        feedDaoConfig.initIdentityScope(type);

        rSSItemDaoConfig = daoConfigMap.get(RSSItemDao.class).clone();
        rSSItemDaoConfig.initIdentityScope(type);

        feedDao = new FeedDao(feedDaoConfig, this);
        rSSItemDao = new RSSItemDao(rSSItemDaoConfig, this);

        registerDao(Feed.class, feedDao);
        registerDao(RSSItem.class, rSSItemDao);
    }
    
    public void clear() {
        feedDaoConfig.getIdentityScope().clear();
        rSSItemDaoConfig.getIdentityScope().clear();
    }

    public FeedDao getFeedDao() {
        return feedDao;
    }

    public RSSItemDao getRSSItemDao() {
        return rSSItemDao;
    }

}
