package me.zsr.feeder.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import me.zsr.feeder.dao.FeedSource;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FEED_SOURCE.
*/
public class FeedSourceDao extends AbstractDao<FeedSource, Long> {

    public static final String TABLENAME = "FEED_SOURCE";

    /**
     * Properties of entity FeedSource.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Url = new Property(2, String.class, "url", false, "URL");
        public final static Property Date = new Property(3, java.util.Date.class, "date", false, "DATE");
        public final static Property Link = new Property(4, String.class, "link", false, "LINK");
        public final static Property Favicon = new Property(5, String.class, "favicon", false, "FAVICON");
        public final static Property Description = new Property(6, String.class, "description", false, "DESCRIPTION");
        public final static Property Reserved = new Property(7, String.class, "reserved", false, "RESERVED");
        public final static Property FeedAccountId = new Property(8, long.class, "feedAccountId", false, "FEED_ACCOUNT_ID");
    };

    private DaoSession daoSession;

    private Query<FeedSource> feedAccount_FeedSourcesQuery;

    public FeedSourceDao(DaoConfig config) {
        super(config);
    }
    
    public FeedSourceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FEED_SOURCE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'TITLE' TEXT NOT NULL ," + // 1: title
                "'URL' TEXT," + // 2: url
                "'DATE' INTEGER," + // 3: date
                "'LINK' TEXT," + // 4: link
                "'FAVICON' TEXT," + // 5: favicon
                "'DESCRIPTION' TEXT," + // 6: description
                "'RESERVED' TEXT," + // 7: reserved
                "'FEED_ACCOUNT_ID' INTEGER NOT NULL );"); // 8: feedAccountId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FEED_SOURCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FeedSource entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(4, date.getTime());
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(5, link);
        }
 
        String favicon = entity.getFavicon();
        if (favicon != null) {
            stmt.bindString(6, favicon);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(7, description);
        }
 
        String reserved = entity.getReserved();
        if (reserved != null) {
            stmt.bindString(8, reserved);
        }
        stmt.bindLong(9, entity.getFeedAccountId());
    }

    @Override
    protected void attachEntity(FeedSource entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FeedSource readEntity(Cursor cursor, int offset) {
        FeedSource entity = new FeedSource( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // url
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // link
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // favicon
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // description
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // reserved
            cursor.getLong(offset + 8) // feedAccountId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FeedSource entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setLink(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFavicon(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDescription(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setReserved(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFeedAccountId(cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FeedSource entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FeedSource entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "feedSources" to-many relationship of FeedAccount. */
    public List<FeedSource> _queryFeedAccount_FeedSources(long feedAccountId) {
        synchronized (this) {
            if (feedAccount_FeedSourcesQuery == null) {
                QueryBuilder<FeedSource> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FeedAccountId.eq(null));
                feedAccount_FeedSourcesQuery = queryBuilder.build();
            }
        }
        Query<FeedSource> query = feedAccount_FeedSourcesQuery.forCurrentThread();
        query.setParameter(0, feedAccountId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFeedAccountDao().getAllColumns());
            builder.append(" FROM FEED_SOURCE T");
            builder.append(" LEFT JOIN FEED_ACCOUNT T0 ON T.'FEED_ACCOUNT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FeedSource loadCurrentDeep(Cursor cursor, boolean lock) {
        FeedSource entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        FeedAccount feedAccount = loadCurrentOther(daoSession.getFeedAccountDao(), cursor, offset);
         if(feedAccount != null) {
            entity.setFeedAccount(feedAccount);
        }

        return entity;    
    }

    public FeedSource loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FeedSource> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FeedSource> list = new ArrayList<FeedSource>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FeedSource> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FeedSource> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
