package me.zsr.feeder.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table RSSITEM.
 */
public class RSSItem {

    private String title;
    private String link;
    private String description;
    private String state;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RSSItem() {
    }

    public RSSItem(String title, String link, String description, String state) {
        this.title = title;
        this.link = link;
        this.description = description;
        this.state = state;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
